### ISSUE TITLE
Não desista do projeto

### ISSUE THREAD

**Issue by AlbertoAlfredo** [carolcodes/tudoficabem.github.io#1]
Não desista do projeto, eu estou disposto a ajudar no que for necessário

**Comment by tamercuba** [comment]
Eu também me interessei muito por esse projeto e estou disposto a ajudar

**Comment by fabiolima** [comment]
to loco pra coda, sorta as issue @carolcodes

**Comment by carolcodes** [comment]
keep calm que sai nos próximos dias :black_heart:

**Comment by paulopenafort** [comment]
Eu também, embora não sei se domino as tecnologias que for usar. Mas disposto a começar

**Comment by vhogemann** [comment]
+1

**Comment by diegosurita** [comment]
+1

**Comment by marceloandriolli** [comment]
Bom dia Carol! Tem provisão pras issues sair? Não desiste do projeto!
